"""Added new table

Revision ID: 55b53b283ce3
Revises: 77d79c4239c9
Create Date: 2025-05-08 22:03:22.138280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b53b283ce3'
down_revision: Union[str, None] = '77d79c4239c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('die_info',
    sa.Column('part_name', sa.String(), nullable=False),
    sa.Column('hr_qty', sa.Integer(), nullable=False),
    sa.Column('qty_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('part_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('die_info')
    # ### end Alembic commands ###
