"""Added new table

Revision ID: 77d79c4239c9
Revises: 
Create Date: 2025-05-04 00:04:33.803262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d79c4239c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_info',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('part_name', sa.String(), nullable=False),
    sa.Column('die_qty', sa.Integer(), nullable=False),
    sa.Column('ot', sa.Integer(), nullable=True),
    sa.Column('tea', sa.Integer(), nullable=True),
    sa.Column('water', sa.Integer(), nullable=True),
    sa.Column('water_payment', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_info')
    # ### end Alembic commands ###
